TURBINE-SLURM.SH
START: 2023-02-06 14:37:24

+ srun /gpfs/fs1/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/gcc-7.1.0/tcl-8.6.8-blvvcoseerw2hsb3d5fhezczx3mjgxy2/bin/tclsh8.6 /lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/experiments/t5-bebop3_1675715837.569274/swift-t-worker_pool_batch.TIy.tic --sim_work_type=0 --batch_size=34 --batch_threshold=20 --worker_pool_id=bebop3 t5-bebop3_1675715837.569274 /tmp/tmpsjrxo__b
TASK START: 931 1675715849.32975
TASK START: 651 1675715849.364576
TASK START: 932 1675715849.369712
TASK START: 929 1675715849.372625
TASK START: 640 1675715849.374371
TASK START: 647 1675715849.37576
TASK START: 648 1675715849.376965
TASK START: 652 1675715849.378372
TASK START: 645 1675715849.383284
TASK START: 653 1675715849.383283
TASK START: 656 1675715849.385035
TASK START: 589 1675715849.389921
TASK START: 650 1675715849.39839
TASK START: 644 1675715849.399518
TASK START: 658 1675715849.401822
TASK START: 662 1675715849.40521
TASK START: 930 1675715849.421196
TASK START: 654 1675715849.423624
TASK START: 655 1675715849.426527
TASK START: 657 1675715849.433646
TASK START: 659 1675715849.436226
TASK START: 935 1675715849.436932
TASK START: 936 1675715849.441652
TASK START: 800 1675715849.446438
TASK START: 802 1675715849.448587
TASK START: 646 1675715849.453293
TASK START: 642 1675715849.454434
TASK START: 933 1675715849.463367
TASK START: 660 1675715849.464384
TASK START: 649 1675715849.465311
TASK START: 934 1675715849.473289
TASK START: 641 1675715849.473812
TASK START: 643 1675715849.473805
TASK START: 928 1675715849.480846
TASK END: 802 1675715852.745887
TASK END: 647 1675715852.785795
TASK END: 641 1675715852.811915
TASK END: 929 1675715852.845939
TASK END: 589 1675715852.864481
TASK END: 655 1675715852.984685
TASK END: 645 1675715852.991867
TASK END: 936 1675715853.019251
TASK END: 652 1675715853.182413
TASK END: 932 1675715853.191409
TASK END: 931 1675715853.265284
TASK END: 657 1675715853.291949
TASK END: 935 1675715854.187642
TASK END: 930 1675715854.524112
TASK END: 800 1675715854.631398
TASK END: 933 1675715855.537829
TASK END: 656 1675715855.586298
TASK END: 650 1675715855.652754
TASK END: 658 1675715858.57269
TASK END: 934 1675715858.937605
TASK END: 648 1675715858.950676
TASK END: 642 1675715859.914122
TASK START: 825 1675715860.285913
TASK START: 917 1675715860.285896
TASK START: 924 1675715860.285892
TASK START: 952 1675715860.285874
TASK START: 827 1675715860.285863
TASK START: 927 1675715860.285999
TASK START: 950 1675715860.28594
TASK START: 544 1675715860.285966
TASK START: 923 1675715860.286018
TASK START: 919 1675715860.286036
TASK START: 920 1675715860.28606
TASK START: 926 1675715860.286087
TASK START: 951 1675715860.28619
TASK START: 824 1675715860.286214
TASK START: 918 1675715860.286205
TASK START: 916 1675715860.286236
TASK START: 921 1675715860.286279
TASK START: 955 1675715860.286395
TASK START: 953 1675715860.28651
TASK START: 949 1675715860.286509
TASK START: 922 1675715860.286544
TASK START: 954 1675715860.286799
TASK END: 954 1675715860.341897
TASK END: 640 1675715860.39745
TASK END: 916 1675715860.416952
TASK END: 827 1675715860.447656
TASK END: 951 1675715860.47916
TASK END: 825 1675715860.571573
TASK END: 927 1675715860.583422
TASK END: 544 1675715860.852937
TASK END: 955 1675715860.912341
TASK END: 949 1675715861.402441
TASK END: 923 1675715861.611793
TASK END: 918 1675715861.822244
TASK END: 920 1675715861.857634
TASK END: 928 1675715862.105343
TASK END: 659 1675715862.235858
TASK END: 917 1675715862.337498
TASK END: 952 1675715864.188836
TASK END: 660 1675715864.422024
TASK END: 824 1675715864.598691
TASK END: 644 1675715864.629657
TASK START: 523 1675715865.630133
TASK START: 837 1675715865.630162
TASK START: 533 1675715865.6302
TASK START: 839 1675715865.630275
TASK START: 526 1675715865.630312
TASK START: 529 1675715865.630354
TASK START: 531 1675715865.630366
TASK START: 838 1675715865.63037
TASK START: 530 1675715865.630364
TASK START: 957 1675715865.630378
TASK START: 535 1675715865.630388
TASK START: 524 1675715865.630433
TASK START: 528 1675715865.630452
TASK START: 532 1675715865.630451
TASK START: 521 1675715865.630466
TASK START: 522 1675715865.630465
TASK START: 525 1675715865.630475
TASK START: 534 1675715865.630587
TASK START: 527 1675715865.630628
TASK START: 537 1675715865.630817
TASK END: 532 1675715865.664405
TASK END: 530 1675715865.808249
TASK END: 529 1675715865.825551
TASK END: 523 1675715865.941622
TASK END: 525 1675715866.069362
TASK END: 534 1675715866.182392
TASK END: 957 1675715866.300495
TASK END: 531 1675715866.319935
TASK END: 522 1675715866.454707
TASK END: 839 1675715867.571369
TASK END: 919 1675715867.874513
TASK END: 838 1675715867.972759
TASK END: 837 1675715868.583577
TASK END: 926 1675715869.138276
TASK END: 537 1675715871.029508
TASK END: 654 1675715871.159075
TASK END: 922 1675715871.506218
TASK END: 527 1675715871.875327
TASK END: 950 1675715872.083346
TASK END: 533 1675715874.112999
TASK START: 856 1675715874.758111
TASK START: 493 1675715874.758141
TASK START: 850 1675715874.758199
TASK START: 860 1675715874.758244
TASK START: 852 1675715874.75825
TASK START: 491 1675715874.758243
TASK START: 853 1675715874.758286
TASK START: 859 1675715874.758271
TASK START: 494 1675715874.758311
TASK START: 851 1675715874.758335
TASK START: 855 1675715874.758368
TASK START: 858 1675715874.758366
TASK START: 489 1675715874.758376
TASK START: 492 1675715874.75841
TASK START: 496 1675715874.758435
TASK START: 854 1675715874.758431
TASK START: 490 1675715874.75841
TASK START: 488 1675715874.758468
TASK START: 495 1675715874.758468
TASK START: 857 1675715874.758478
TASK END: 857 1675715874.776791
TASK END: 524 1675715874.94807
TASK END: 856 1675715875.224427
TASK END: 858 1675715875.56631
TASK END: 850 1675715875.570242
TASK END: 860 1675715875.714389
TASK END: 490 1675715876.443118
TASK END: 526 1675715876.50537
TASK END: 853 1675715877.253241
TASK END: 528 1675715878.274907
TASK END: 489 1675715878.561284
TASK END: 662 1675715878.734114
TASK END: 496 1675715879.391972
TASK END: 493 1675715879.95278
TASK END: 535 1675715882.194246
TASK END: 651 1675715884.169652
TASK END: 494 1675715884.518359
TASK END: 488 1675715884.851429
TASK END: 492 1675715885.152232
TASK END: 491 1675715885.237893
TASK END: 855 1675715887.991858
TASK END: 924 1675715888.180523
TASK END: 649 1675715895.785532
eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


TASK END: 643 1675715896.831252
TASK END: 953 1675715899.630585
eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


TASK END: 859 1675715902.449244
TASK END: 921 1675715903.990533
eq_swift.query_task_n error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 76, in query_tasks_n
    eq_sql = _create_eqsql(retry_threshold)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


loop.swift: got EQ_ABORT: exiting!
worker pool: normal exit.
eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


TASK END: 653 1675715911.005887
eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


TASK END: 854 1675715915.363903
eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


TASK END: 851 1675715916.771081
eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


TASK END: 852 1675715927.720813
TASK END: 495 1675715928.009354
TASK END: 646 1675715929.069702
eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


TASK END: 521 1675716605.253056
eq_swift.report_task error Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 73, in connect
    self.conn = psycopg2.connect("dbname="+self.dbname,
  File "/home/collier/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 52, in report_task
    eq_sql = _create_eqsql(retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/eqsql_examples/asynch_repriority/swift/ext/eq_swift.py", line 19, in _create_eqsql
    return eq.init_eqsql(host, user, port, db_name, retry_threshold, log_level)
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 195, in init_eqsql
    raise e
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/eq.py", line 190, in init_eqsql
    db.connect()
  File "/lcrc/project/EMEWS/bebop/repos/EQ-SQL/python/eqsql/db_tools.py", line 79, in connect
    raise ConnectionException(e)
eqsql.db_tools.ConnectionException: connection to server at "beboplogin3.lcrc.anl.gov" (10.70.128.7), port 3149 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


python: initializing...
python: initializing...
python: initializing...
python: initializing...
turbine finalizing at: 775.936
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
ADLB Total Elapsed Time: 775.937
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...
python: initializing...

MPIEXEC TIME: 779.545
EXIT CODE: 0
COMPLETE: 2023-02-06 14:50:24
[3;J[H[2J